### ISSUE TITLE
Max externals does not work on Windows 10 in Max 8, but works in Rewire or Max4Live

### ISSUE THREAD

**Issue by mourendxu** [expertsleepersltd/externals#1]
This is a problem Windows 10 on a PC running the latest firmware, audio drivers and windows update. The problem has existed for more than half a year now. I have previously reported it on Muffwiggler to no avail.

Max externals downloaded from Expert Sleepers' website does not work in Max 8, if using only Max 8 to output to Audio Interface. 

My interface is ES9, I have ES5, ESX8GT, ESX8CV connected.

When I am outputting from Max 8, where Max 8 is using the ES9 interface:
  Gate info and Voltage info(piped through an esx8encoder first) sent to ES5, to the proper ports for the various modules, using the correct formatting and to the correct output, 7 & 8 on my ES9, results in gibberish on my ES5, ESX8GT, ESX8CV modules.

However, when I use the same externals in Max4Live, or even the same patch but audio channeled via Rewire to Reaper, and Reaper outputs to 7 & 8, then everything works just fine.

So, I am guessing it has something to do with how the audio is being outputted. 

It would be great to get a fix. 

Thanks.

**Comment by expertsleepers** [comment]
Mac or PC?

**Comment by mourendxu** [comment]
Ah, my subject title said Windows 10, I forgot to add that to the body of the post. My bad.

It's a PC running Windows 10 with the latest drivers, firmware, etc. It has been this way since I got the module, which was about half a yr ago.

**Comment by expertsleepers** [comment]
This is similar to
https://github.com/VCVRack/Rack/issues/1539

So it's not the externals that are wrong, it's how max is providing the audio to the drivers.

Another user had the same problem, and he said:
> Adding a very small value did the trick. Before writing to you I tried multiplying, but that didn't work. Just tested with addition and voilá. The value I had to add was 1/10000000, indeed very small.

So this is adding a small value to the external output before hitting the dac~.

**Comment by mourendxu** [comment]
Ohh.. magical. Yes that did fix it. Thank you! 

I guess it was just a floating point issue. :D

**Comment by expertsleepers** [comment]
Cool.
